apiVersion: v1
kind: Service              
metadata:
  name: jupyter-notebook
spec:
  type: LoadBalancer
  loadBalancerIP: 34.174.183.197
  ports:
  - port: 8888               
    protocol: TCP          
    targetPort: 8888         
  selector:                
    app: jupyter-notebook
