apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: datanode2
  name: datanode2
spec:
  ports:
    - name: "9865"
      port: 9865
      targetPort: 9865
  selector:
    io.kompose.service: datanode2
status:
  loadBalancer: {}
